// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/host.proto

/*
Package video_host is a generated protocol buffer package.

It is generated from these files:
	proto/host.proto

It has these top-level messages:
	Request
	Response
	GetVideoRequest
	GetVideoResponse
*/
package video_host

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Title       string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string                `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	DateCreated string                `protobuf:"bytes,3,opt,name=date_created,json=dateCreated" json:"date_created,omitempty"`
	Views       uint64                `protobuf:"varint,4,opt,name=views" json:"views,omitempty"`
	Likes       uint64                `protobuf:"varint,5,opt,name=likes" json:"likes,omitempty"`
	Dislikes    uint64                `protobuf:"varint,6,opt,name=dislikes" json:"dislikes,omitempty"`
	Resolutions *Response_Resolutions `protobuf:"bytes,7,opt,name=resolutions" json:"resolutions,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *Response) GetViews() uint64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Response) GetLikes() uint64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Response) GetDislikes() uint64 {
	if m != nil {
		return m.Dislikes
	}
	return 0
}

func (m *Response) GetResolutions() *Response_Resolutions {
	if m != nil {
		return m.Resolutions
	}
	return nil
}

type Response_Resolutions struct {
	Q144P  bool `protobuf:"varint,1,opt,name=q144p" json:"q144p,omitempty"`
	Q240P  bool `protobuf:"varint,2,opt,name=q240p" json:"q240p,omitempty"`
	Q360P  bool `protobuf:"varint,3,opt,name=q360p" json:"q360p,omitempty"`
	Q480P  bool `protobuf:"varint,4,opt,name=q480p" json:"q480p,omitempty"`
	Q720P  bool `protobuf:"varint,5,opt,name=q720p" json:"q720p,omitempty"`
	Q1080P bool `protobuf:"varint,6,opt,name=q1080p" json:"q1080p,omitempty"`
}

func (m *Response_Resolutions) Reset()                    { *m = Response_Resolutions{} }
func (m *Response_Resolutions) String() string            { return proto.CompactTextString(m) }
func (*Response_Resolutions) ProtoMessage()               {}
func (*Response_Resolutions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Resolutions) GetQ144P() bool {
	if m != nil {
		return m.Q144P
	}
	return false
}

func (m *Response_Resolutions) GetQ240P() bool {
	if m != nil {
		return m.Q240P
	}
	return false
}

func (m *Response_Resolutions) GetQ360P() bool {
	if m != nil {
		return m.Q360P
	}
	return false
}

func (m *Response_Resolutions) GetQ480P() bool {
	if m != nil {
		return m.Q480P
	}
	return false
}

func (m *Response_Resolutions) GetQ720P() bool {
	if m != nil {
		return m.Q720P
	}
	return false
}

func (m *Response_Resolutions) GetQ1080P() bool {
	if m != nil {
		return m.Q1080P
	}
	return false
}

type GetVideoRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Resolution string `protobuf:"bytes,2,opt,name=resolution" json:"resolution,omitempty"`
}

func (m *GetVideoRequest) Reset()                    { *m = GetVideoRequest{} }
func (m *GetVideoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVideoRequest) ProtoMessage()               {}
func (*GetVideoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetVideoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetVideoRequest) GetResolution() string {
	if m != nil {
		return m.Resolution
	}
	return ""
}

type GetVideoResponse struct {
	PresignedUrl string `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl" json:"presigned_url,omitempty"`
}

func (m *GetVideoResponse) Reset()                    { *m = GetVideoResponse{} }
func (m *GetVideoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVideoResponse) ProtoMessage()               {}
func (*GetVideoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetVideoResponse) GetPresignedUrl() string {
	if m != nil {
		return m.PresignedUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "video_host.Request")
	proto.RegisterType((*Response)(nil), "video_host.Response")
	proto.RegisterType((*Response_Resolutions)(nil), "video_host.Response.Resolutions")
	proto.RegisterType((*GetVideoRequest)(nil), "video_host.GetVideoRequest")
	proto.RegisterType((*GetVideoResponse)(nil), "video_host.GetVideoResponse")
}

func init() { proto.RegisterFile("proto/host.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0x49, 0xb7, 0x9b, 0x0d, 0x93, 0x02, 0x2b, 0xb3, 0x42, 0x21, 0x20, 0x14, 0xc2, 0xa5,
	0xa7, 0x92, 0xa6, 0x11, 0x45, 0xe2, 0x04, 0x1c, 0x0a, 0xd7, 0x48, 0x70, 0xad, 0x4a, 0x3d, 0x80,
	0x45, 0x14, 0xbb, 0xb1, 0x5b, 0x7e, 0x02, 0x17, 0x6e, 0xfc, 0x61, 0x34, 0x93, 0xa4, 0x0d, 0xa8,
	0x7b, 0xf3, 0xfb, 0xde, 0xf8, 0xc5, 0xcf, 0x0e, 0x5c, 0x9b, 0x46, 0x3b, 0xfd, 0xf2, 0xbb, 0xb6,
	0x6e, 0xc6, 0x4b, 0x01, 0x07, 0x25, 0x51, 0xaf, 0x89, 0xa4, 0x8f, 0xe1, 0xaa, 0xc4, 0xdd, 0x1e,
	0xad, 0x13, 0xf7, 0x61, 0xa4, 0x64, 0xe4, 0x25, 0xde, 0xf4, 0x6e, 0x39, 0x52, 0x32, 0xfd, 0x75,
	0x01, 0x41, 0x89, 0xd6, 0xe8, 0xda, 0xa2, 0xb8, 0x81, 0x4b, 0xa7, 0x5c, 0x85, 0x9d, 0xdf, 0x0a,
	0x91, 0x40, 0x28, 0xd1, 0x6e, 0x1b, 0x65, 0x9c, 0xd2, 0x75, 0x34, 0x62, 0x6f, 0x88, 0xc4, 0x73,
	0x98, 0xc8, 0x8d, 0xc3, 0xf5, 0xb6, 0xc1, 0x8d, 0x43, 0x19, 0x5d, 0x74, 0x23, 0x1b, 0x87, 0xef,
	0x5b, 0x44, 0xd1, 0x07, 0x85, 0x3f, 0x6d, 0x34, 0x4e, 0xbc, 0xe9, 0xb8, 0x6c, 0x05, 0xd1, 0x4a,
	0xfd, 0x40, 0x1b, 0x5d, 0xb6, 0x94, 0x85, 0x88, 0x21, 0x90, 0xca, 0xb6, 0x86, 0xcf, 0xc6, 0x51,
	0x8b, 0x77, 0x10, 0x36, 0x68, 0x75, 0xb5, 0xa7, 0x0f, 0xdb, 0xe8, 0x2a, 0xf1, 0xa6, 0x61, 0x9e,
	0xcc, 0x4e, 0x65, 0x67, 0x7d, 0x1b, 0x5a, 0xf4, 0x73, 0xe5, 0x70, 0x53, 0xfc, 0xc7, 0x83, 0x70,
	0x60, 0xd2, 0x29, 0x76, 0xf3, 0xa2, 0x30, 0x5c, 0x3b, 0x28, 0x5b, 0xc1, 0x34, 0x2f, 0x32, 0xc3,
	0x85, 0x89, 0x92, 0x60, 0xba, 0x78, 0x95, 0x19, 0xee, 0x48, 0x94, 0x04, 0xd3, 0xe2, 0x75, 0x66,
	0xb8, 0x1d, 0x51, 0x12, 0x4c, 0x97, 0x79, 0x66, 0xb8, 0x1d, 0x51, 0x12, 0xe2, 0x11, 0xf8, 0xbb,
	0x79, 0x46, 0xc3, 0x3e, 0xe3, 0x4e, 0xa5, 0x6f, 0xe1, 0xc1, 0x0a, 0xdd, 0x67, 0x2a, 0x72, 0xcb,
	0x63, 0x89, 0x67, 0x00, 0xa7, 0x1e, 0xdd, 0x43, 0x0c, 0x48, 0xba, 0x84, 0xeb, 0x53, 0x44, 0xf7,
	0xa6, 0x2f, 0xe0, 0x9e, 0x69, 0xd0, 0xaa, 0x6f, 0x35, 0xca, 0xf5, 0xbe, 0xa9, 0xba, 0xb8, 0xc9,
	0x11, 0x7e, 0x6a, 0xaa, 0xfc, 0xb7, 0x07, 0xe3, 0x0f, 0xda, 0x3a, 0xf1, 0x06, 0x26, 0x7d, 0xc2,
	0xc7, 0xfa, 0xab, 0x16, 0x0f, 0xff, 0xbd, 0x59, 0x3e, 0x56, 0x7c, 0x73, 0xee, 0xba, 0xd3, 0x3b,
	0x62, 0x05, 0x41, 0xbf, 0x59, 0x3c, 0x19, 0xce, 0xfc, 0xd7, 0x2b, 0x7e, 0x7a, 0xde, 0xec, 0x83,
	0xbe, 0xf8, 0xfc, 0x0b, 0x2f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x28, 0x50, 0x19, 0x0d, 0xd6,
	0x02, 0x00, 0x00,
}
